### ISSUE TITLE
connection timeout without description, Network error

### ISSUE THREAD

**Issue by madhukiranbr** [jenkinsci/stashnotifier-plugin#140]
plugin version : 1.11.4 and 1.11
Bit bucket version : v4.5.2

`<HTML><HEAD>
<meta http-equiv="Pragma" content="no-cache">
<TITLE>Network Error</TITLE>
</HEAD>
<BODY>
<img src=>
<FONT face="Helvetica">
<big><strong></strong></big><BR>
</FONT>
<blockquote>
<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>
<FONT face="Helvetica">
<big>Network Error (tcp_error)</big>
<BR>
<BR>
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
A communication error occurred: Operation timed out
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica" SIZE="2">
<BR>

</FONT>
</TD></TR>
</TABLE>
</blockquote>
xyz
</BODY></HTML>`

**Jenkins log:**

Caught exception evaluating: h.filterDescriptors(it,attrs.descriptors) in /configure. Reason: java.lang.NullPointerException
java.lang.NullPointerException
	at hudson.model.DescriptorVisibilityFilter.apply(DescriptorVisibilityFilter.java:72)
...

**Comment by madhukiranbr** [comment]
I am able to ping and telnet to bitbucket server. 
I don't see how this is a network issue

**Comment by scaytrase** [comment]
hi, @madhukiranbr 
Are you able to perform REST API calls manually using tools like cURL from jenkins host?

https://developer.atlassian.com/static/rest/bitbucket-server/4.12.1/bitbucket-rest.html

**Comment by madhukiranbr** [comment]
The Curl Rest api call succeeded as expected

`
jenkinshost$ cat test.json
{
        "state": "FAILED",
        "key": "TEST",
        "name": "demo",
        "url": "http://<orgname>:7990/projects/TEST/repos/demo-java",
        "description": "Test update from cURL"
}

jenkinshost$ curl -sL -w%{http_code} -u user:pass -H "Content-Type: application/json" -X POST http://<orgname>:7990/rest/build-status/1.0/commits/f1388477f9b3d395ec1db46c6c1e105ddc3e8a91 -d @test.json
204
`

**Comment by scaytrase** [comment]
Can you verify your jenkins proxy settings? Also can you give me a full stack trace of the exception?

**Comment by madhukiranbr** [comment]
Its most likely my proxy settings. Will reopen issue if I encounter this again.

The error could be more verbose with an indication to check proxy

**Comment by madhukiranbr** [comment]
https://github.com/jenkinsci/stashnotifier-plugin/pull/143

**Comment by linehammer** [comment]
I would suggest you to repair the TCP/IP stack in your system and check whether the issue is resolved. Follow the steps mentioned below.

a. Click on Start, Programs and then Accessories and right click on Command Prompt, select "Run as Administrator" to open a command prompt.

b. In the command prompt, type in the bolded text, one command after the other, pressing Enter between each of them:

- Reset WINSOCK entries to installation defaults:netsh winsock reset catalog

- Reset IPv4 TCP/IP stack to installation defaults:netsh int ipv4 reset reset.log

- Reset IPv6 [TCP](http://net-informations.com/q/diff/tcpudp.html)/IP stack to installation defaults:netsh int ipv6 reset reset.log

c. Reboot the machine.
