### ISSUE TITLE
After a failed build, re-running the build does not update Stash status to green

### ISSUE THREAD

**Issue by oenningj** [jenkinsci/stashnotifier-plugin#16]
According to Stash documentation,
https://developer.atlassian.com/stash/docs/latest/how-tos/updating-build-status-for-commits.html

On the section "False alarm", I have exactly the same situation, a broken build due to infrastucture. I then re-run the build (no further commits), and the build status on Stash does not update to "green". Even though the build list shows Stash has been notified. (ie, I have 2 failed builds and 1 green build), but it shows as "failed build".

I also have "keep repeated builds in stash" selected.

I'm using Stash 2.5, with stashnotifier 1.5.

Thanks
Jonny

**Comment by DidierLoiseau** [comment]
FYI, this issue is referenced directly in [Bitbucket’s documentation](https://support.atlassian.com/bitbucket-data-center/kb/commit-build-status-is-always-red-even-if-other-builds-succeed/). It seems however that they got the resolution wrong:

> To get around this, configure your Jenkins plugin with "keep repeated builds in bitbucket" checked. See [this discussion for more details](https://github.com/jenkinsci/stashnotifier-plugin/issues/16).

If I’m not wrong, it should be _unchecked_, and `includeBuildNumberInKey` should be `false` if calling the plugin directly.

I think it would be nice if the documentation mentioned that one should keep it `false` if they want to have the “Minimum successful builds” check enabled for Pull Requests in Bitbucket – otherwise any temporary issue on Jenkins’ side can only be solved through a dummy commit to satisfy the successful build requirement.
