### ISSUE TITLE
Upgrade to 4.0.0-rc of Jenkins Git Plugin can't be updated to

### ISSUE THREAD

**Issue by riy** [jenkinsci/stashnotifier-plugin#221]
The latest v1.16 release is [declaring Jenkins Git Plugin v4.0.0-rc](https://github.com/jenkinsci/stashnotifier-plugin/commit/a6c43e016fcbeaeec9191b1b864bb4fdd4219352#diff-600376dffeb79835ede4a0b285078036L107) as a dependency.

When trying to update to v1.16 we're getting this message:
![grafik](https://user-images.githubusercontent.com/903321/52644838-e3721500-2edf-11e9-9d3e-29e5e20f46b1.png)

We're on Jenkins v2.164 and we're stuck with v3.9.3 of Git plugin as of now. I believe Jenkins won't let us update to to an RC version of a plugin, so I believe the dependency to `v4.0.0-rc` should be reverted to an earlier stable version.

**Comment by scaytrase** [comment]
There is nothing special on 1.16 but deps update only. So feel free to pin 1.15. I'll keep this open to deal this when we'll have new features in the release

**Comment by riy** [comment]
Thank you for the quick response, Pavel!
Can you please elaborate on "pin v1.15"? How can I pin it? You mean by downgrading the plugin to v1.15?

**Comment by scaytrase** [comment]
Yes, downgrade and fix version. I hope this was called `pin` some time ago in plugin manager, but might be wrong.

**Comment by HubMiner** [comment]
This Issue with "git plugin" puts "stash notifier" into "unable to load" condition, thus there is no option to pin it to 1.15 via Jenkins GUI.  This forces me to shut down Jenkins and to manually manipulate plugins.

To prevent this pain from spreading, please consider creating next version of stash notifier pointing to an existing version of git plugin.

**Comment by ewypych** [comment]
There is no option to quick "downgrade" as the plugin is not visible in Plugin Manager. Of course, you can download the previous version (.hpi file), but I don't think that it's the best idea – this should be fixed on your, plugin Developers' side. The only solution which makes sense is to revert dependency to the earlier version. I also faced this problem.

**Comment by goostleek** [comment]
The plugin cannot be easily downgraded to the previously installed version because only loaded plugins can be pinned. The current version (1.16) cannot be loaded because its dependency (Git Plugin 4.0.0-rc) cannot be satisfied so the Stash Notifier is not visible under `/pluginManager/installed` tab. The only way to recover from this broken release is to downgrade manually by downloading the previous release from [here](https://github.com/jenkinsci/stashnotifier-plugin/releases/download/1.15/stashNotifier.hpi) and uploading it using `/pluginManager/advanced` tab. That will make the plugin working again.

I really don't understand #218 as it makes the plugin dependent on non-existent dependency (Git plugin 4.0.0-rc) which is not available on the Jenkins Update Center. Even dedicated [Git plugin site](https://plugins.jenkins.io/git) says the latest version is 3.9.3 (not 4.0.0-rc). Having that in mind it's impossible to use Stash Notifier plugin in the latest version (1.16). Installing it using Jenkins Update Center is pointless (not to mention confusing) as it won't be working due to unsatisfied dependency. Additionally, some people update Jenkins periodically every a couple of days or weeks to have all the Jenkins plugins up-to-date ensuring smooth Jenkins operation. Updating to Stash Notifier 1.16 will simply break their Jenkins instance as Stash Notifier will not work anymore.

From my perspective, the current Stash Notifier release (1.16) is broken. Could you please elaborate on why this release rely on non-existent dependency?

**Comment by scaytrase** [comment]
It was existent before :( 

https://github.com/jenkins-infra/update-center2/pull/258

We'll revert these changes

**Comment by scaytrase** [comment]
Until then everyone can use HPI from release page

https://github.com/jenkinsci/stashnotifier-plugin/releases/tag/1.15

**Comment by scaytrase** [comment]
I've released 1.17. Check it please

**Comment by HubMiner** [comment]
We upgraded to latest: it is alive again, thank you for quick fix!
