### ISSUE TITLE
Stash notifies when using the conditional build step

### ISSUE THREAD

**Issue by KyleLNicholls** [jenkinsci/stashnotifier-plugin#30]
I'm using the conditional build step with Stash Notify. If the conditional build step prevents the Stash notification then in Stash I get "build in progress" indefinitely.
Regardless of the conditional build step Stash gets notified at the beginning of a build that it's in progress.

Maybe have the plugin not do the initial notification if conditional build step is being used? Or have an option to not use the initial notification all together?

**Comment by michaelajr** [comment]
This is an issue for me as well. My deployment job can run from an upstream build job - and in that case I have the GIT_COMMIT ID. But it can also run manually - pulling down a user-specified version from our maven repo. In this case - I do not have a GIT_COMMIT ID. I'd really love to use the Conditional Build step to determine if I have a GIT_COMMIT ID - and if so - notify Stash. As the OP indicates this does not seem to work because of the "build in progress" notification, which can not be wrapped in a conditional build step.  Hoping for an easy fix, like an opt-out of the "build in progress" notification, or recognize that it is part of a conditional build step - and check if the step is enabled before notifying.

**Comment by scaytrase** [comment]
I think opt-out pre-build notifying is an options, so closing in favor of #53

**Comment by scaytrase** [comment]
You could try [latest build](https://github.com/jenkinsci/stashnotifier-plugin/releases/tag/1.9-alpha2) to check an option which disables pre-build notification. It's off by default for BC.
