### ISSUE TITLE
PR-initiated build actually builds the destination, not the source

### ISSUE THREAD

**Issue by haliphax** [jenkinsci/stashnotifier-plugin#83]
I've set up Jenkins and Stash (actually BitBucket Server), and configured this plugin to poll Pull Requests in Stash and comment on the build status. Everything looked great, but when I was checking the Jenkins build, it was actually building the last known commit on the *destination* for the PR, not the commit hash from the *source*.

Example:
- Repository `dest` has branch `master` at commit `1234`
- I fork it to my `source` repo, add a file, and commit, resulting in commit `abcde`
- I create a PR to the `dest` repo
- Jenkins comments on the PR saying all is good, and the comment shows the correct commit hashes
- When I check the Jenkins build, it shows that it actually built `1234`, and my new file is not listed in the "Changes" section (in fact, `abcde` is not listed anywhere in the console output for the git commands at all; I can plainly see it checking out revision `1234`, instead)

Have I missed some important configuration setting?

Thanks! Love the service so far! If I can manage to get this kink worked out, we will be using it at the university I work for, and take our source control game to a whole new level.

**Comment by scaytrase** [comment]
I'm not sure this problem is about this plugin, but I recommend you to look thru the [automerge build status plugin](https://confluence.atlassian.com/stash/using-pull-requests-in-stash-299570995.html) to see how correctly reference pull-requests

**Comment by haliphax** [comment]
I understand how pull requests work, though I may not have done a great job of explaining it. Regardless, the issue stands. Without writing a bunch of my own shell script in Jenkins, it does not build the PR commit hash; it builds the `HEAD` commit hash of the destination. If this still isn't sufficient to get you to take this issue seriously, I'll try to better compose my thoughts on Monday morning with screenshots and such.

**Comment by scaytrase** [comment]
I'll never take this issue seriosly, because you are addressing the wrong plugin. The fact I want say to you - you are building incorrect branch. You should specify `:.*pull-requests/.*/merge` refspec to get jenkins checkout correct PR merged state branch

**Comment by ashnazg** [comment]
One key thing to check when configuring for PRs is the refspecs settings,
since Stash has those under different "sub-refs".
CRB

**Comment by haliphax** [comment]
How was I expected to know that the refspec needs to be tinkered with? I figured: this is a Stash plugin. I'm using Stash. The defaults should be sane. Pointing this out in the documentation/administration screen blurb for the plugin would be incredibly helpful.

**Comment by ashnazg** [comment]
Configuring the refspec and the branches to build is not part of the stashnotifier plugin... it's basic configuration of the Jenkins job when Git is your SCM.  Thus there is nothing "Stash-ish" about this part of the job configuration.

Stash has its pull requests in a different refspec than plain old master and develop live on.  This is their design choice, not Jenkins'.  So, as Stash users, it's up to us.  To configure the job for a pull request, you have to set the Refspec (under Source Code Management --> Git --> Repositories --> Advanced) to `+refs/pull-requests/*:refs/remotes/origin/pull-requests/*`.  *Also*, for Branches to Build, you need `origin/pull-requests/*/from`.

Now, this is the _other_ angle with regard to PRs when considering the one mentioned by @scaytrase.  Stash holds your PR on the "from" branch, while it implicltly performs a merge against the PR's target on its "merge" branch.  So, really each PR has _two_ potential builds.  I have my Jenkins builds such that I have a FROM-side build that runs first, and if it succeeds, it runs a MERGE-side build.  Since the PR itself only displays the FROM-side commits, it's only that FROM-side build notification that can ever be seen in Stash... the closest thing that Stash displays of that MERGE-side branch is if your PR shows "merge conflicts" on the PR itself (this check is why I think Stash does that MERGE-side under the covers).

Hope that helps...

**Comment by scaytrase** [comment]
thanks @ashnazg for the full explaination. I think I can close this.

**Comment by haliphax** [comment]
I think that, if the refspec for Stash is different than that of any other Git-driven SCM, then it should at least be pointed out somewhere obvious. This plugin is, after all, the *Stash* Notifier. At any rate, thank you for your help; both of you. I may stick with the PowerShell script I've been using to work around this, since I think it will be more obvious to other developers what is happening in the build for the PRs.

**Comment by ashnazg** [comment]
What I think we're failing to help you understand is that it is Stash that is giving Jenkins the commit SHA to build, irrespective of the notifier plugin.  Which SHA that Stash hands to Jenkins has everything to do with which refspec _and_ branchToBuild that you have configured on your Jenkins job (not the notifier plugin).  The Stash Notifier only knows how to take that same SHA and say "hey Stash, Jenkins says Pass/Fail on SHA abc".  Having that refspec+branchToBuild set correctly to point to the branch you want built (and reported on) is the key.

I think the default behavior from an unspecified refspec/branchToBuild might be to just watch origin/*, which would pick up master, but not the PRs since they're on a separate refspec path.  So, when your job would poll, Stash would pick up the latest master SHA, and that's what got built.  What's odd to me is that the build notification _did_ reach your PR, because my understanding has always been that the MERGE-side result of the PR is _not_ the same as the destination branch itself.  Now, if you're seeing the build notification on your PR _after it is accepted and merged_, then it does make sense to me.  However, if you were seeing build notifications against a master SHA but visible on your PR, then I'm at a loss.

I will say that you're not the first person to get frustrated with Stash + Jenkins regarding PRs, because Stash didn't really document how to find those PRs.  As best I can tell, people had to reverse-engineer their way into discovering that the PRs all live in Stash on those /pull-request/ refspecs.  But once you know to configure the jobs this way, you're golden... I have several dozen repos that have two Jenkins jobs per repo, one for the FROM branch (exact code that's on the PR) and one for the MERGE branch (the expected merge result if the PR is accepted and merged).

Also, a big caveat here is that since Atlassian considers the PR refspec to not be "public API", they have changed it at least once (from v1 to v2 of Stash, it changed... and I had to dig to discover what they renamed their PR refspecs to).  I'm still on v2, so I don't know if they changed it again on v3, much less on their v4 jump to becoming Bitbucket.  However, I would guess that their method of using a separate refspec for internally managing PRs is probably still in place.

**Comment by haliphax** [comment]
Yeah, I think I was conflating this with the Pull Request Notifier plugin. At any rate, I do now have it building the "merge" branch of the pull request, which is ultimately what I was looking for. As far as I can tell, it is still using the format you specified in your post. I think that writing the PowerShell for pulling, merging, and building based on the build parameters was helpful in demonstrating to me what was really going on, but it is much cleaner now that I have it building the right target from the get-go without any extraneous scripts.

Seriously, thank you both for your help. This will be an invaluable weapon in our (brand new to the organization) source control arsenal. I'm having to drag several developers along with me who have zero-to-little experience with this sort of thing, so the more streamlined I can make it, the better.

:thumbsup:

**Comment by ashnazg** [comment]
:thumbsup: ++  :)
