### ISSUE TITLE
Select what repository to notify when using Multiple repositories

### ISSUE THREAD

**Issue by Sajfer** [jenkinsci/stashnotifier-plugin#87]
When using the Multiple SCMs Plugin for jenkins together with Stash notifier, all repositories are notified of the build status. It would be very useful to be able to select what repositories that get notified.

Use case:
A jenkins project that use two repositories, one that is the base system, and one that is project specific. If build fails, only the project specific repository should be notified. The base system is built and tested in another jenkins project and should not be set as failed because a project specific build failed.

**Comment by scaytrase** [comment]
At the moment you can specify only single commit of single stash server. There is no repository means, only commit hash. Specifying commits from repository you need you can notify certain repository only.

Multiple repositories should be possible with [multiple notifiers implemented](https://github.com/jenkinsci/stashnotifier-plugin/issues/61) or commit-list instead of single commit

**Comment by scaytrase** [comment]
Recorded as separate future enhansement

**Comment by riy** [comment]
I have posted a possible workaround/solution to this issue [here](https://github.com/jenkinsci/stashnotifier-plugin/issues/173#issuecomment-574112284).
